name: 'test_vvc_deployment'
version: '1.0.0'
config-version: 2

profile: 'test_vvc'

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_vvc_deployment:
    +materialized: table
